/**
 * Shared test-database infrastructure (generated by dev-env).
 *
 * Isolation strategy: a migrated template database is cloned into one private
 * database per Vitest worker; every test starts on an empty database because an
 * afterEach TRUNCATEs all user tables. Parallelism is file-level across workers,
 * and each worker owns its own database, so truncation can never cross workers.
 *
 * `test.concurrent` is UNSAFE in any DB-touching file: concurrent tests within a
 * single file share that worker's database, so one test's truncate would wipe
 * another's rows mid-flight. Keep DB tests sequential.
 *
 * CRITICAL: never statically import the app's Prisma singleton here (a type-only
 * import is fine). truncateAllTables() is gated on `globalThis.prisma`, which the
 * app's lib/prisma sets only once a test file imports the singleton — so pure-unit
 * files that never touch the DB pay nothing. Constructing a fresh PrismaClient for
 * admin work is fine; it does not touch that global.
 */

import { execSync } from "child_process";
import crypto from "crypto";
import fs from "fs";
import os from "os";
import path from "path";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/generated/prisma/client";

export const BASE_DB = "arbini_family_test";
export const TEMPLATE_DB = `${BASE_DB}_template`;

/** Name of a worker's private database for the given tinypool slot. */
export function workerDb(poolId: string | number): string {
  return `${BASE_DB}_w${poolId}`;
}

/** Return `url` with its database name (pathname) swapped for `name`. */
export function withDbName(url: string, name: string): string {
  const parsed = new URL(url);
  parsed.pathname = `/${name}`;
  return parsed.toString();
}

/**
 * PrismaClient pointed at the `postgres` maintenance database, for CREATE/DROP
 * DATABASE statements (which cannot run against a database you're connected to).
 */
export function adminClient(): PrismaClient {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");
  // Prisma 7's pg driver owns the pool. Cap the admin client at a single connection:
  // it only runs serial CREATE/DROP DATABASE, and one pool per Vitest worker at the
  // pg default (10) would exhaust Postgres across many workers.
  return new PrismaClient({
    adapter: new PrismaPg({
      connectionString: withDbName(url, "postgres"),
      max: 1,
    }),
  });
}

function collectMigrationFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...collectMigrationFiles(full));
    else files.push(full);
  }
  return files;
}

/** sha256 over every file path + contents under prisma/migrations. */
export function migrationsHash(): string {
  const dir = path.join(process.cwd(), "prisma", "migrations");
  const hash = crypto.createHash("sha256");
  for (const file of collectMigrationFiles(dir).sort()) {
    hash.update(path.relative(dir, file));
    hash.update("\0");
    hash.update(fs.readFileSync(file));
    hash.update("\0");
  }
  return hash.digest("hex");
}

/**
 * Rebuild the template database only when the migrations hash differs from the
 * value stored in `COMMENT ON DATABASE`. The migrate runs in a child process that
 * exits, so no connection lingers to block cloning the template.
 */
export async function ensureTemplateDatabase(
  admin: PrismaClient,
): Promise<void> {
  const hash = migrationsHash();

  const rows = await admin.$queryRaw<Array<{ comment: string | null }>>`
    SELECT shobj_description(oid, 'pg_database') AS comment
    FROM pg_database
    WHERE datname = ${TEMPLATE_DB}
  `;
  if (rows[0]?.comment === hash) return;

  await admin.$executeRawUnsafe(
    `DROP DATABASE IF EXISTS "${TEMPLATE_DB}" WITH (FORCE)`,
  );
  await admin.$executeRawUnsafe(`CREATE DATABASE "${TEMPLATE_DB}"`);

  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");
  const templateUrl = withDbName(url, TEMPLATE_DB);
  // pnpm exec resolves the prisma binary regardless of pnpm's hoisting layout, unlike a
  // hardcoded ./node_modules/.bin path.
  execSync("pnpm exec prisma migrate deploy", {
    stdio: "inherit",
    env: {
      ...process.env,
      DATABASE_URL: templateUrl,
      DATABASE_URL_UNPOOLED: templateUrl,
    },
  });

  await admin.$executeRawUnsafe(
    `COMMENT ON DATABASE "${TEMPLATE_DB}" IS '${hash}'`,
  );
}

/** Drop and re-clone one worker database per slot from the template. */
export async function provisionWorkerDatabases(
  admin: PrismaClient,
  count: number,
): Promise<void> {
  for (let i = 1; i <= count; i++) {
    const db = workerDb(i);
    await admin.$executeRawUnsafe(
      `DROP DATABASE IF EXISTS "${db}" WITH (FORCE)`,
    );
    await admin.$executeRawUnsafe(
      `CREATE DATABASE "${db}" TEMPLATE "${TEMPLATE_DB}"`,
    );
  }
}

/** Provision enough databases for the configured workers or the host's cores. */
export function defaultWorkerCount(configured: number): number {
  return Math.max(configured || 1, os.availableParallelism());
}

// Discovered once per worker process, then reused for every truncate.
let cachedTruncateSql: string | null = null;

/**
 * TRUNCATE every user table in one statement. No-op unless a test file has
 * imported the app's Prisma singleton (which sets globalThis.prisma) — pure-unit
 * files pay nothing.
 */
export async function truncateAllTables(): Promise<void> {
  const prisma = (globalThis as { prisma?: PrismaClient }).prisma;
  if (!prisma) return;

  if (cachedTruncateSql === null) {
    const tables = await prisma.$queryRaw<Array<{ tablename: string }>>`
      SELECT tablename
      FROM pg_tables
      WHERE schemaname = 'public'
        AND tablename NOT LIKE '_prisma_%'
    `;
    cachedTruncateSql =
      tables.length === 0
        ? ""
        : `TRUNCATE TABLE ${tables
            .map((t) => `"public"."${t.tablename}"`)
            .join(", ")} RESTART IDENTITY CASCADE`;
  }

  if (cachedTruncateSql) await prisma.$executeRawUnsafe(cachedTruncateSql);
}

/** Disconnect the app singleton if this worker ever constructed it. */
export async function disconnectAppPrisma(): Promise<void> {
  const prisma = (globalThis as { prisma?: PrismaClient }).prisma;
  if (prisma) await prisma.$disconnect();
}
