// Generated by dev-env — run: pnpm dev-env plan arbini.family
// Centralize environment access: every process.env read goes through the validated modules in
// lib/env/, so a missing required variable fails the build instead of surfacing later as an
// undefined. eslint.config.mjs spreads this last so it cannot be overridden locally.
//
// Named rather than an anonymous array literal: eslint-config-next enables
// import/no-anonymous-default-export, which would warn on every lint run in every repo.
const devEnvEslint = [
  {
    name: "dev-env/tool.env@1",
    files: ["**/*.ts", "**/*.tsx"],
    ignores: [
      // The env modules are the one place allowed to read process.env.
      "lib/env/**",
      // Must read the process.env.NEXT_RUNTIME literal so Next can tree-shake per-runtime code.
      "instrumentation.ts",
      // Tests stub the environment directly.
      "**/*.test.ts",
      "**/*.test.tsx",
      // Prisma CLI bootstrap; runs before .env.local is loaded.
      "prisma.config.ts",
      // dev-env-owned Vitest harness.
      "vitest.config.ts",
      "vitest.setup.ts",
      // dev-env-owned parallel test-database harness; rewrites DATABASE_URL per worker.
      "vitest.env-setup.ts",
      "vitest.global-setup.ts",
      "test/db.ts",
    ],
    rules: {
      "no-restricted-properties": [
        "error",
        {
          object: "process",
          property: "env",
          message:
            "Read environment through lib/env/server.ts or lib/env/client.ts.",
        },
      ],
    },
  },
];

export default devEnvEslint;
