#!/usr/bin/env bash
# Generated by dev-env — run: pnpm dev-env plan arbini.family
set -euo pipefail
[ "${CONDUCTOR_IS_LOCAL:-1}" = "1" ] || exit 0
cd "$(dirname "$0")/.."
PROJECT_DIR="$(pwd -P)"
CONTAINER="$(docker ps -aq --filter "label=devcontainer.local_folder=$PROJECT_DIR" | head -n1)"
[ -n "$CONTAINER" ] || { echo "No workspace container found; nothing to clean."; exit 0; }
PROJECT="$(docker inspect "$CONTAINER" --format '{{index .Config.Labels "com.docker.compose.project"}}')"
docker compose --project-name "$PROJECT" -f .devcontainer/docker-compose.yml down --volumes --remove-orphans --rmi local
echo "Docker resources removed for $PROJECT."
