#!/usr/bin/env bash
# Generated by dev-env — run: pnpm dev-env plan arbini.family
set -euo pipefail
RUN_ID="${1:-}"; shift || true
[ "${1:-}" = "--" ] || { echo "usage: $0 <id> -- <command>" >&2; exit 2; }
shift
ROOT="${CONDUCTOR_WORKSPACE_PATH:-$PWD}"
cd "$(cd "$ROOT" && pwd -P)"
mkdir -p .context
CONTAINER="$(docker ps -q --filter "label=devcontainer.local_folder=$PWD" | head -n1)"
[ -n "$CONTAINER" ] || { echo "No running devcontainer" >&2; exit 1; }
MARKER=".context/conductor-run-$RUN_ID"
TOKEN="$RUN_ID-$$-$(date +%s)"
cleanup() {
  [ -s "$MARKER" ] || return 0
  read -r cid pgid token < "$MARKER" || true
  [ "$cid" = "$CONTAINER" ] && docker exec "$CONTAINER" bash -c 'kill -HUP -- "-$1" 2>/dev/null || true; sleep .05; kill -KILL -- "-$1" 2>/dev/null || true' _ "$pgid" >/dev/null 2>&1 || true
  rm -f "$MARKER"
}
cleanup
trap 'cleanup; exit 129' HUP
trap 'cleanup; exit 130' INT
trap 'cleanup; exit 143' TERM
trap cleanup EXIT
devcontainer exec --workspace-folder "$PWD" bash -c '
  token="$1"; marker="$2"; cid="$3"; shift 3
  env CONDUCTOR_RUN_TOKEN="$token" setsid "$@" & pid=$!
  printf "%s %s %s\n" "$cid" "$pid" "$token" > "$marker"
  wait "$pid"
' _ "$TOKEN" "$MARKER" "$CONTAINER" "$@"
