#!/usr/bin/env bash
# Generated by dev-env — run: pnpm dev-env plan arbini.family
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "${CONDUCTOR_WORKSPACE_PATH:-$PWD}"
DEVPORT="${DEV_ENV_PORT:-${CONDUCTOR_PORT:-}}"
RECREATE=()
if [ -n "$DEVPORT" ]; then
  CONTAINER="$(docker ps -aq --filter "label=devcontainer.local_folder=$(pwd -P)" | head -n1)"
  if [ -n "$CONTAINER" ]; then
    CURRENT="$(docker inspect "$CONTAINER" --format '{{range .Config.Env}}{{println .}}{{end}}' | sed -n 's/^PORT=//p' | head -n1)"
    [ "$CURRENT" = "$DEVPORT" ] || RECREATE=(--remove-existing-container)
  fi
fi
devcontainer up --workspace-folder . "${RECREATE[@]}" >/dev/null
PORT_BASE="$DEVPORT"
[ -n "$PORT_BASE" ] || PORT_BASE="$(devcontainer exec --workspace-folder . printenv PORT | tr -d '\r')"
PORT=$((PORT_BASE + 2))
exec "$SCRIPT_DIR/run-container-command.sh" studio -- pnpm prisma studio --port "$PORT" --hostname 0.0.0.0 --browser none
