#!/usr/bin/env bash
# Generated by dev-env — run: pnpm dev-env plan arbini.family
set -euo pipefail
[ "${CONDUCTOR_IS_LOCAL:-1}" = "1" ] || exit 0
cd "$(dirname "$0")/.."
devcontainer up --workspace-folder . >/dev/null
echo "Workspace ready. Press Run (dev)."
