FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
RUN curl -fsSL https://starship.rs/install.sh | sh -s -- -y
RUN npm install -g npm@latest
RUN npm install -g @anthropic-ai/claude-code
