#!/usr/bin/env bash
# Generated by dev-env — run: pnpm dev-env plan arbini.family
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"
OVERRIDE_FILE="$SCRIPT_DIR/docker-compose.worktree.yml"
docker volume inspect pnpm-store-shared >/dev/null 2>&1 || docker volume create pnpm-store-shared >/dev/null

PORT_BASE="${DEV_ENV_PORT:-${CONDUCTOR_PORT:-}}"
if [ -z "$PORT_BASE" ]; then
  KEY="$(cd "$WORKSPACE_DIR" && pwd -P)"
  PORT_BASE=$((20000 + 0x$(printf '%s' "$KEY" | shasum | cut -c1-4) % 10000))
fi
APP_PORT=$PORT_BASE
PG_PORT=$((PORT_BASE + 1))
STUDIO_PORT=$((PORT_BASE + 2))
EMAIL_PORT=$((PORT_BASE + 3))
FALLBACK_PORT=$((PORT_BASE + 4))

COMMON_MOUNT=""
if [ -f "$WORKSPACE_DIR/.git" ]; then
  COMMON_DIR="$(git -C "$WORKSPACE_DIR" rev-parse --git-common-dir)"
  [[ "$COMMON_DIR" = /* ]] || COMMON_DIR="$(cd "$WORKSPACE_DIR/$COMMON_DIR" && pwd)"
  COMMON_MOUNT="$(printf '    volumes:\n      - \"%s:%s:cached\"' "$COMMON_DIR" "$COMMON_DIR")"
fi

cat > "$OVERRIDE_FILE" <<EOF
# Generated by initialize.sh — do not edit.
services:
  app:
    environment:
      PORT: "$APP_PORT"
${COMMON_MOUNT}
    ports:
      - "$APP_PORT:$APP_PORT"
      - "$FALLBACK_PORT:3000"
EOF

echo "initialize: app=$APP_PORT from workspace port base $PORT_BASE"
