#!/usr/bin/env bash
# Generated by dev-env — run: pnpm dev-env plan arbini.family
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"
OVERRIDE_FILE="$SCRIPT_DIR/docker-compose.worktree.yml"
docker volume inspect pnpm-store-shared >/dev/null 2>&1 || docker volume create pnpm-store-shared >/dev/null

PORT_BASE="${DEV_ENV_PORT:-${CONDUCTOR_PORT:-}}"
if [ -z "$PORT_BASE" ]; then
  KEY="$(cd "$WORKSPACE_DIR" && pwd -P)"
  PORT_BASE=$((20000 + 0x$(printf '%s' "$KEY" | shasum | cut -c1-4) % 10000))
fi
APP_PORT=$PORT_BASE
PG_PORT=$((PORT_BASE + 1))
STUDIO_PORT=$((PORT_BASE + 2))
EMAIL_PORT=$((PORT_BASE + 3))
FALLBACK_PORT=$((PORT_BASE + 4))
INNGEST_PORT=$((PORT_BASE + 5))

# Docker rolls the network endpoint back when it cannot publish a port, leaving the container
# running with no interfaces at all. That surfaces much later as EAI_AGAIN on every registry
# request rather than as a port error, so refuse to start instead of handing back a dead container.
# A rebuild runs while this workspace's own containers still hold the ports, so only a *different*
# compose project counts as a conflict.
OWN_PROJECT=""
OWN_CONTAINER="$(docker ps -aq --filter "label=devcontainer.local_folder=$(cd "$WORKSPACE_DIR" && pwd -P)" | head -n1 || true)"
if [ -n "$OWN_CONTAINER" ]; then
  OWN_PROJECT="$(docker inspect "$OWN_CONTAINER" --format '{{index .Config.Labels "com.docker.compose.project"}}' 2>/dev/null || true)"
fi
PORT_CONFLICT=""
for CHECK_PORT in $APP_PORT $FALLBACK_PORT $PG_PORT $STUDIO_PORT $EMAIL_PORT; do
  # A heredoc rather than a pipe: the loop must run in this shell so PORT_CONFLICT survives it.
  while IFS=' ' read -r BUSY_NAME BUSY_PROJECT; do
    [ -n "$BUSY_NAME" ] || continue
    if [ -n "$OWN_PROJECT" ] && [ "$BUSY_PROJECT" = "$OWN_PROJECT" ]; then
      continue
    fi
    PORT_CONFLICT="$PORT_CONFLICT  port $CHECK_PORT is already published by $BUSY_NAME (compose project ${BUSY_PROJECT:-none})
"
  done <<EOF
$(docker ps --filter "publish=$CHECK_PORT" --format '{{.Names}} {{.Label "com.docker.compose.project"}}' 2>/dev/null || true)
EOF
done
if [ -n "$PORT_CONFLICT" ]; then
  echo "initialize: port base $PORT_BASE is unavailable:" >&2
  printf '%s' "$PORT_CONFLICT" >&2
  echo "Stop the container(s) above, or set DEV_ENV_PORT to a free base, then retry." >&2
  exit 1
fi

COMMON_MOUNT=""
if [ -f "$WORKSPACE_DIR/.git" ]; then
  COMMON_DIR="$(git -C "$WORKSPACE_DIR" rev-parse --git-common-dir)"
  [[ "$COMMON_DIR" = /* ]] || COMMON_DIR="$(cd "$WORKSPACE_DIR/$COMMON_DIR" && pwd)"
  COMMON_MOUNT="$(printf '    volumes:\n      - \"%s:%s:cached\"' "$COMMON_DIR" "$COMMON_DIR")"
fi

cat > "$OVERRIDE_FILE" <<EOF
# Generated by initialize.sh — do not edit.
services:
  app:
    environment:
      PORT: "$APP_PORT"
${COMMON_MOUNT}
  db:
    ports:
      - "$APP_PORT:$APP_PORT"
      - "$FALLBACK_PORT:3000"
      - "$PG_PORT:5432"
      - "$STUDIO_PORT:$STUDIO_PORT"
      - "$EMAIL_PORT:3001"
EOF

# The file above is rewritten on every run, but `devcontainer up` starts an already-created
# container with `docker compose up -d --no-recreate`, and Docker fixes port bindings at creation.
# A container that predates a change to the publish list therefore keeps the old bindings while
# this file claims the new ones -- the override reads correct and the port answers nothing, which
# is a worse failure than a missing line because there is nothing to notice. Report it instead.
#
# A warning rather than an exit: unlike a port conflict, the container is working for everything it
# already published, and this script also runs on the --remove-existing-container invocation that
# fixes the problem, so failing here would stand in front of the remedy.
#
# --filter publish= is not usable for this. It matches only running containers, so a stopped one --
# which `up` would restart with exactly these stale bindings -- would look like it publishes nothing
# and report every port. HostConfig.PortBindings is what survives the container being stopped.
if [ -n "$OWN_PROJECT" ]; then
  PUBLISHED=""
  for OWN_ID in $(docker ps -aq --filter "label=com.docker.compose.project=$OWN_PROJECT" 2>/dev/null); do
    PUBLISHED="$PUBLISHED $(docker inspect "$OWN_ID" --format '{{range $port, $bindings := .HostConfig.PortBindings}}{{range $bindings}}{{.HostPort}} {{end}}{{end}}' 2>/dev/null || true)"
  done
  STALE_PORTS=""
  for WANT_PORT in $APP_PORT $FALLBACK_PORT $PG_PORT $STUDIO_PORT $EMAIL_PORT; do
    case " $PUBLISHED " in
      *" $WANT_PORT "*) ;;
      *) STALE_PORTS="$STALE_PORTS $WANT_PORT" ;;
    esac
  done
  # devcontainer runs this script *before* it removes the old container, so a run that is already
  # recreating would otherwise be told to re-run itself. Read the invoking command to tell the two
  # apart. If that cannot be read the warning still prints: a redundant nudge is a smaller failure
  # than staying silent about a port that answers nothing.
  RECREATING=""
  case "$(ps -o args= -p $PPID 2>/dev/null || true)" in
    *--remove-existing-container*) RECREATING="1" ;;
  esac
  if [ -n "$STALE_PORTS" ] && [ -z "$RECREATING" ]; then
    echo "initialize: this workspace's container was created before the current port list and does not publish:$STALE_PORTS" >&2
    echo "  The override file is up to date, but Docker only applies published ports when a container is created." >&2
    echo "  Recreate it to pick them up: devcontainer up --workspace-folder . --remove-existing-container" >&2
  fi
fi

echo "initialize: app=$APP_PORT from workspace port base $PORT_BASE"
