#!/usr/bin/env zsh
# Generated by dev-env — run: pnpm dev-env plan arbini.family
set -e
if [ "${1:-}" = "--prepare" ]; then exit 0; fi
pnpm install --frozen-lockfile
# --install stops here. Dependency-only runs (dev-env apply) use a transient container and must
# not depend on a provisioned database or a browser download.
#
# Written as an if rather than a test-and-exit one-liner: a project with no post-install step ends
# on this line, and a false test would leave the script exiting 1, failing postCreateCommand.
if [ "${1:-}" = "--install" ]; then exit 0; fi
pnpm prisma:initialize
