/**
 * Prints the environment block to paste into this project's Cursor cloud environment
 * (generated by dev-env — run: pnpm dev-env plan arbini.family).
 *
 * Sources, in ascending precedence:
 *
 *   - .devcontainer/.env       committed, but only the devcontainer loads it
 *   - .devcontainer/.env.local gitignored
 *   - .env.local               gitignored
 *
 * The committed root .env is deliberately absent: the cloud agent has the file and reads it.
 *
 * Values are printed in full, so run this where you would read those files anyway. The block goes
 * to stdout and every note to stderr, so a pipe copies only the block:
 *
 *   devcontainer exec --workspace-folder . pnpm --silent env:cloud | pbcopy
 *
 * This has no dependencies and reads nothing but those files, so it also runs straight off the host
 * when the container is down — `node scripts/env-cloud.mjs | pbcopy`.
 */

import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");

const SOURCES = [
  ".devcontainer/.env",
  ".devcontainer/.env.local",
  ".env.local",
];

// Names that must not be pasted, each with the reason it is handled elsewhere.
const EXCLUDED = new Map([]);

// Families of names that must not be pasted, matched by shape.
const EXCLUDED_PATTERNS = [
  [
    /^[A-Za-z_]*(DATABASE|POSTGRES)[A-Za-z_]*URL[A-Za-z_]*$/,
    "the cloud VM has its own PostgreSQL, and .cursor/install.sh points the datasource at it",
  ],
  [
    /^VERCEL(_|$)/,
    "injected by Vercel at build time; a pulled copy is stale metadata, and VERCEL/VERCEL_ENV would tell the app it is running on Vercel",
  ],
  [
    /^(TURBO|NX)_/,
    "local build-tool toggles that arrive with `vercel env pull`, not application configuration",
  ],
];

function excludedReason(name) {
  if (EXCLUDED.has(name)) return EXCLUDED.get(name);
  return EXCLUDED_PATTERNS.find(([pattern]) => pattern.test(name))?.[1] ?? null;
}

// Deliberately parsed rather than sourced: sourcing executes whatever the file happens to contain,
// and no value here is ever expanded or interpolated.
function read(file) {
  const full = path.join(root, file);
  if (!fs.existsSync(full)) return [];
  return fs
    .readFileSync(full, "utf8")
    .split("\n")
    .flatMap((line) => {
      const match = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/.exec(
        line,
      );
      if (!match) return [];
      const raw = match[2].trim();
      const quoted = /^(['"\`])(.*)\1$/.exec(raw);
      return [{ name: match[1], value: quoted ? quoted[2] : raw }];
    });
}

const values = new Map();
for (const file of SOURCES)
  for (const { name, value } of read(file)) values.set(name, value);

// The cloud agent has the committed .env and reads it, so a local value identical to what is
// already there is noise in the block rather than configuration.
const committed = new Map(
  read(".env").map((entry) => [entry.name, entry.value]),
);

const block = [];
// Grouped by reason rather than listed per name: one `vercel env pull` contributes two dozen
// variables that are all held back for the same reason, and a flat list buries the rest.
const skipped = new Map();
for (const [name, value] of [...values].sort(([a], [b]) =>
  a.localeCompare(b),
)) {
  const reason =
    excludedReason(name) ??
    (committed.get(name) === value
      ? "identical to the committed .env, which the cloud agent already reads"
      : null);
  if (reason) skipped.set(reason, [...(skipped.get(reason) ?? []), name]);
  else block.push(`${name}=${value}`);
}

// .env.example is the project's declared contract. Anything it names that no local file sets has to
// come from somewhere else, and would otherwise surface as a failed import on the first cloud run.
const known = new Set([...values.keys(), ...committed.keys()]);
const missing = read(".env.example")
  .map((entry) => entry.name)
  .filter((name) => !known.has(name) && !excludedReason(name));

console.log(block.join("\n"));
if (skipped.size)
  console.error(
    `\nSkipped:\n${[...skipped]
      .map(([reason, names]) => `  ${names.join(", ")}\n    ${reason}`)
      .join("\n")}`,
  );
if (missing.length)
  console.error(
    `\nNamed in .env.example but set in no local file:\n${missing.map((name) => `  ${name}`).join("\n")}`,
  );
