import type { z } from "zod";

// Generated by dev-env (tool.env@1). Do not edit — regenerated on every apply.
// The variable schemas live in ./server.ts and ./client.ts, which dev-env scaffolds once and
// then leaves alone; this file is only the shared parsing machinery.

/**
 * Treat empty-string vars as unset. `.env` files commonly disable a feature by leaving the value
 * blank (`OPENAI_API_KEY=`), which arrives as `""` — that must read as "not provided", so an
 * `.optional()` var passes while a blank *required* var still fails.
 */
export function withoutEmptyStrings(
  source: Record<string, string | undefined>,
): Record<string, string | undefined> {
  const out: Record<string, string | undefined> = {};
  for (const [key, value] of Object.entries(source)) {
    out[key] = value === "" ? undefined : value;
  }
  return out;
}

/**
 * Parse a schema and report *every* problem at once, keyed by variable name. Reporting one issue
 * at a time turns a fresh clone into a guess-and-retry loop; naming all of them plus the example
 * file makes the first failure actionable.
 */
export function parseEnv<T extends z.ZodType>(
  schema: T,
  source: Record<string, string | undefined>,
  label: string,
): z.infer<T> {
  const parsed = schema.safeParse(source);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map(
        (issue) => `  - ${issue.path.join(".") || "(root)"}: ${issue.message}`,
      )
      .join("\n");
    throw new Error(
      `Invalid ${label} environment variables:\n${issues}\n` +
        "See .env.example for the full list of variables this app needs.",
    );
  }
  return parsed.data;
}
